
[tool.black]
line-length = 100
target-version = ["py310","py311","py312"]
exclude = [
  "/build/",
  "/dist/",
  "/.venv/",
  "/venv/",
  "/docker/",
]

[tool.isort]
profile = "black"
line_length = 100
skip = ["build","dist","docker",".venv","venv"]
